name: Scrape

on:
  schedule:
    - cron: "0 */1 * * *" #top of every hour
  workflow_dispatch:

jobs: 
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pipenv
      run: pipx install pipenv
    - uses: actions/setup-python@v2
      with: 
        python-version: '3.9'
        cache: 'pipenv'
    - run: pipenv install --python `which python`
    - name: Run scraper
      run: pipenv run jupyter execute mpd_cad_scrape.ipynb
    - name: Add and commit
      id: add_commit
      uses: EndBug/add-and-commit@v8
      with:
        committer_name: Automated
        committer_email: actions@users.noreply.github.com
        message: "Latest data"
    - name: Push
      run: git push
    - name: Slack Notification on SUCCESS
      if: success()
      uses: tokorom/action-slack-incoming-webhook@main
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        text: MPD calls for service successfully downloaded.
    - name: Slack Notification on FAILURE
      if: failure()
      uses: tokorom/action-slack-incoming-webhook@main
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        text: ':red-card: Scrape failed'
    