name: Makefile CI

on:
  #schedule:
    #- cron: "0 12 * * 2" #every 12th hour on the second day of the week (noon every tuesday)
  workflow_dispatch:

jobs: 
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: dependencies
      run: make dependencies

    - name: run full script
      run: make update

    - name: Add and commit
      id: add_commit
      uses: EndBug/add-and-commit@v8
      with:
        committer_name: Automated
        committer_email: actions@users.noreply.github.com
        message: "Data Updated"
    - name: Push	
      run: git push


  # need to add all AWS keys to secrets (settings > secrets > actions)
  # upload:
  #   needs: scrape
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - uses: shallwefootball/upload-s3-action@master
  #       with:
  #         aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
  #         aws_bucket: ${{ secrets.AWS_S3_BUCKET }}
  #         source_dir: 'data/final'
  #         destination_dir: 'project-feeds'