name: Makefile CI

on:
  #schedule:
    #- cron: "0 */1 * * *" #top of every hour
  workflow_dispatch:

jobs: 
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: make dependencies
    - name: download data
      run: make download